### ISSUE TITLE
creating a source `from_sql` is broken

### ISSUE THREAD

**Issue by lloydtabb** [malloydata/malloy#1076]
Trying to create a source from sql is broken...  Seems pretty urgent unless there is a work around I'm not seeing.

The code below generates the following error.

```
Error(s) compiling model:
FILE: internal://internal.malloy
line 1: Must use 'from_sql()' for sql source 'order_items_table
  | query: order_items_table->by_sequence
  |        ^
```
The code.
```
sql: airports_sql is {
  select: """
    select 
      *
      , ROW_NUMBER() OVER (PARTITION BY state ORDER BY elevation) as rn
    FROM malloy-data.malloytest.airports
  """
  connection: "bigquery"
}

// Broken:  This eroneously reports an error
source: order_items_table is from_sql(airports_sql) {
// Broken:  This eroneously reports an error
  query: by_sequence is {
    group_by: rn
    aggregate: order_count is count()
  }
}
```

**Comment by lloydtabb** [comment]
@christopherswenson tagging you to maybe look at it since it is your Monday already.

**Comment by christopherswenson** [comment]
Taking a look...

**Comment by christopherswenson** [comment]
So, the error that I'm seeing is that when you "Preview" `order_items_table` or "Run" `by_sequence` in VSCode using the code lenses, you get an error like `Must use 'from_sql()' for sql source 'order_items_table`.

When you run the "Preview" or "Run" code lenses, we use the "extending model" mode of translation. So we translate the file as-is, then as to translate a file like `query: order_items_table -> { project: *; limit: 20 }` while extending the model for the file. 

When doing so, we take the existing model def and attempt to import it into the translator's world. As part of that, we try to decide whether the thing being imported is a SQL block or a source. 

The relevant code is here:

https://github.com/malloydata/malloy/blob/8fe12b87ce6052b8c9fd5d1fc6df0bb69f2479d6/packages/malloy/src/lang/ast/types/malloy-element.ts#L379-L400

The problem is, in the translated `ModelDef`, the `order_items_table` and `airports_sql` don't actually have any good way to distinguish whether they are sources or SQL Blocks. We're just checking whether the struct source is a SQL query, which it is in both cases.

Here's a test that reproduces:

```
test('source based on SQL block', () => {
    const docParse = new TestTranslator(`
      sql: s is {
        select: """SELECT * FROM t"""
      }
      source: t is from_sql(s) {
        query: q is {
          group_by: n
        }
      }
    `);
    const xr1 = docParse.translate();
    expect(xr1).toMatchObject({
      compileSQL: {select: [{sql: 'SELECT * FROM t'}]},
    });
    const sql = xr1?.compileSQL;
    if (sql === undefined) throw new Error('Expected SQL to be defined');
    docParse.update({
      compileSQL: {
        [sql.name]: {
          type: 'struct',
          name: sql.name,
          dialect: 'standardsql',
          structSource: {
            type: 'sql',
            method: 'subquery',
            sqlBlock: {
              type: 'sqlBlock',
              ...sql,
              selectStr: sql.select.filter(s => typeof s === 'string').join(''),
            },
          },
          structRelationship: {
            type: 'basetable',
            connectionName: sql.connection || 'bigquery',
          },
          fields: [{type: 'number', name: 'n'}],
        },
      },
    });
    const x = docParse.translate();
    const md = x.translated?.modelDef;
    expect(md).toBeDefined();
    if (md === undefined) throw new Error('Unexpected');
    const docParse2 = new TestTranslator(`
      query: t -> { project: * }
    `);
    const res = docParse2.translate(md);
    expect(docParse2).modelCompiled();
  });
  ```
  
Note: I had to update the `TestTranslator`'s `translate` method to accept an extending model:

```
  translate(extendingModel?: ModelDef): TranslateResponse {
    return super.translate(extendingModel ?? this.internalModel);
  }
```

**Comment by christopherswenson** [comment]
@mtoy-googly-moogly @lloydtabb I'm not sure what the best answer here is. Currently we store "whether this struct is a SQL block" in the `ModelEnt`'s `ent.sqlType`. Maybe instead that belongs in the `StructDef` itself (`sd.isSQLBlock`).

**Comment by christopherswenson** [comment]
As for a workaround, you should just be able to write 

```
// Equivalent to "Preview"
query: order_items_table -> { project: *; limit: 20 }

// Equivalent to "Run" for `by_sequence`
query: order_items_table -> by_sequence
```

**Comment by mtoy-googly-moogly** [comment]
This is my bug and I completely undersrtand it

**Comment by mtoy-googly-moogly** [comment]
The bug is, if you derive a source from a source which was originally an SQL block, the code still things it is an SQL block because, as Chris points out, that information is stored in the wrong place. I am making a PR to work around this.
