### ISSUE TITLE
Trailing refinements in Sources not working properly

### ISSUE THREAD

**Issue by carlineng** [malloydata/malloy#1459]
### What happens?

I have a view:

```
  view: sale_metrics is {
    aggregate: total_sales, percent_of_sales, total_gross_margin, order_item_count
  }
```

I create a view based off this using the "lens" pattern:

```
  view: top_brands is {
    top: 5
    group_by: inventory_items.product_brand
  } + sale_metrics
```

I create another view based on this one:

```
  view: top_brands2 is top_brands
```

When I run `top_brands2`, the `sale_metrics` are not included in the query.

### To Reproduce

Execute the view in this branch of the malloy-samples repo:

https://github.com/malloydata/malloy-samples/blob/405ec454de7f3df1a1dc0bb41b458698069c4573/ecommerce/ecommerce.malloy#L100

### OS:

macOS

### Malloy Client:

local VSCode

### Malloy Client Version:

v0.3.1698786291

### Database Connection:

DuckDB

**Comment by christopherswenson** [comment]
Okay, so the problem is that when we process the refinements of a view, we remove the refinements property at the end:

https://github.com/malloydata/malloy/blob/main/packages/malloy/src/lang/ast/elements/pipeline-desc.ts#L109

Then, the same view (`top_brands`) is recompiled as part of the definition of the second view (`top_brands2` in your example), but because the refinements were removed, they are not included.

**Comment by christopherswenson** [comment]
It also seems like somewhat of a performance issue if every reference to a view recompiles that view from scratch. Maybe we should be caching the result?
