### ISSUE TITLE
we need some kind of 'unknown' type that malloy knows about but can't do anything with.

### ISSUE THREAD

**Issue by lloydtabb** [malloydata/malloy#900]
There are types like GEOGRAPHY in BigQuery that cannot currently deal with.  We should have an UNKNOWN type that will be ignored on a project: * but can be used in function calls.  Many databases have weird types we aren't likely to support.

**Comment by mtoy-googly-moogly** [comment]
It feels like the plan is to throw some hacky handwave at the geography type, which we have been ignoring for years, just because it broke the docs build. I'd like to think about this before we do anything, I am not sure I agree with the proposed solution.

**Comment by mtoy-googly-moogly** [comment]
It would be SUPER quick to simply edit the unsupported types of of the schema until we decide how to handle them, for example.

**Comment by christopherswenson** [comment]
Another short-term benefit (maybe?) of an unknown type is that we could make SQL functions return unknown if we don't know the type, rather than guessing.

**Comment by mtoy-googly-moogly** [comment]
1) I am resolutely against SQL functions returning unknown types instead of inferred types. There needs to be a SQL function apocalypse at which point when can change how we deal with them at some point, between now and then, I am pretty unmovable on the idea. What we have now is a placeholder and what we would have if we changed the return to unknown is a universe where every call to an SQL function would have to be typecast, and I can't imagine ever being OK with that.

2) I am OK with the schema reader returning `{ type: "unsupported", unsupportedType: "location" }` for location data, or for any other type that the runtime does not support. I would also like for more types to be supported. This would then mean that we could get the behavior that lloyd wants, if I call a function and pass an unsupported type, the return would be unsupported. There is no way to cast to an unsupported type though, which is one reason why I want us to just support all the types, when we write a dialect.

2a) We could do

```
(some expression)::`unsupportedTypeName`
```

to cast to types we know nothing about

3) I am OK with passing unsupported types to functions and having functions which are passed an unsupported type returning an unsupported type

4) I don't understand what happens with these in the renderer.

**Comment by mtoy-googly-moogly** [comment]
It almost feels like there should be some type info in the dialect which maps types in the database to types in Malloy ... currently this is kind of ad hoc, but making a formal part of the dialect seems like a good idea.

**Comment by mtoy-googly-moogly** [comment]
I've got #920 queued up and ready to merge, which will allow people to use tables with unsupported fields, even though they can't get at the data in the unsupported fields.

**Comment by mtoy-googly-moogly** [comment]
This is now done with https://github.com/malloydata/malloy/pull/1019
